export default [
  "Andalusian classical music",
  "Indian classical music",
  "Korean court music",
  "Persian classical music",
  "Western classical music",
  "Early music",
  "Medieval music",
  "Ars antiqua",
  "Ars nova",
  "Ars subtilior",
  "Renaissance music",
  "Baroque music",
  "Galant music",
  "Classical period",
  "Romantic music",
  "20th",
  "Modernism",
  "Impressionism",
  "Neoclassicism",
  "High modernism",
  "Postmodern music",
  "Experimental music",
  "Contemporary classical music",
  "Minimal music",
  "Danger music",
  "Electroacoustic",
  "Lo-fi",
  "Musique concrète",
  "Noise",
  "Outsider music",
  "Industrial music",
  "Progressive music",
  "African blues",
  "Blues rock",
  "Blues shouter",
  "British blues",
  "Canadian blues",
  "Chicago blues",
  "Classic female blues",
  "Contemporary R&B",
  "Country blues",
  "Delta blues",
  "Detroit blues",
  "Electric blues",
  "Gospel blues",
  "Hill country blues",
  "Hokum blues",
  "Jump blues",
  "Kansas City blues",
  "Louisiana blues",
  "Memphis blues",
  "New Orleans blues",
  "Piedmont blues",
  "Punk blues",
  "Rhythm and blues",
  "Doo-wop",
  "Soul blues",
  "St. Louis blues",
  "Swamp blues",
  "Texas blues",
  "West Coast blues",
  "Alternative country",
  "Cowpunk",
  "Americana",
  "Australian country",
  "Bakersfield sound",
  "Bluegrass",
  "Progressive bluegrass",
  "Reactionary bluegrass",
  "Country blues",
  "Country pop",
  "Country rap",
  "Country rock",
  "Cajun",
  "Cajun fiddle",
  "Christian country",
  "Close harmony",
  "Dansband",
  "Hokum",
  "Honky tonk",
  "Instrumental country",
  "Nashville sound",
  "Neotraditional country",
  "New Mexico music",
  "Outlaw country",
  "Progressive country",
  "Red dirt",
  "Rockabilly",
  "Hellbilly",
  "Psychobilly",
  "Sertanejo",
  "Tejano",
  "Texas country",
  "Traditional country music",
  "Truck-driving country",
  "Western (Cowboy)",
  "Cowboy pop",
  "New Mexico",
  "Texas country",
  "Tejano",
  "Western swing",
  "Zydeco",
  "Background music",
  "Elevator music",
  "Barococo",
  "Beautiful music",
  "Chill-out",
  "Furniture music",
  "Light music",
  "Lounge music",
  "Middle of the road",
  "New-age music",
  "Ambient",
  "Ambient dub",
  "Dark ambient",
  "Ambient industrial",
  "Dungeon synth",
  "Isolationism",
  "Drone",
  "Illbient",
  "New-age",
  "Andean new-age",
  "Neoclassical new-age",
  "Space music",
  "Reductionism",
  "Lowercase",
  "Onkyokei",
  "Bass music",
  "Footwork",
  "Future bass",
  "Kawaii future bass",
  "Jungle terror",
  "UK bass",
  "Wave",
  "Hardwave",
  "Breakbeat",
  "Acid breaks",
  "Baltimore club",
  "Jersey club",
  "Philly club",
  "Big beat",
  "Breakbeat hardcore",
  "4-beat",
  "Darkcore",
  "Hardcore breaks",
  "Broken beat",
  "Florida breaks",
  "Nu skool breaks",
  "Progressive breaks",
  "Psychedelic breakbeat",
  "Chill-out",
  "Downtempo",
  "Psybient",
  "Psydub",
  "Trip hop",
  "Trip rock",
  "Chopped and screwed",
  "Disco",
  "Afro/cosmic music",
  "Electro-disco",
  "Hi-NRG",
  "Eurobeat",
  "Eurodance",
  "Italo dance",
  "Italo disco",
  "Spacesynth",
  "Space disco",
  "Eurodisco",
  "Nu-disco",
  "Post-disco",
  "Boogie",
  "City pop",
  "Disco edits",
  "Drum and bass",
  "Darkstep",
  "Drumfunk",
  "Drumstep",
  "Hardstep",
  "Intelligent drum and bass",
  "Atmospheric drum and bass",
  "Jazzstep",
  "Jump-up",
  "Liquid funk",
  "Neurofunk",
  "Sambass",
  "Techstep",
  "Dub",
  "Dub poetry",
  "Dubtronica",
  "Electroacoustic music",
  "Acousmatic music",
  "Electroacoustic improvisation",
  "Live electronics",
  "Musique concrète",
  "Soundscape",
  "Electronic rock",
  "Dance-rock",
  "Alternative dance",
  "Madchester",
  "Baggy",
  "New rave",
  "Dance-punk",
  "Krautrock",
  "New wave",
  "Cold wave",
  "Dark wave",
  "Neoclassical dark wave",
  "Neue Deutsche Todeskunst",
  "Ethereal wave",
  "Nu-gaze",
  "Minimal wave",
  "Neue Deutsche Welle",
  "New romantic",
  "Sophisti-pop",
  "Synth-pop",
  "Dance-pop",
  "Disco polo",
  "Electroclash",
  "Electropop",
  "Hyperpop",
  "Indietronica",
  "Post-rock",
  "Space rock",
  "Synth-metal",
  "Electrogrind",
  "Electronicore",
  "Synth-punk",
  "Electronica",
  "Folktronica",
  "Jazztronica",
  "Laptronica",
  "Livetronica",
  "Progressive electronic",
  "Kosmische musik",
  "Ethnic electronica",
  "Asian underground",
  "African electronic dance music",
  "Afrobeats",
  "Azonto",
  "Coupé-décalé",
  "Kuduro",
  "Mahraganat",
  "Shangaan electro",
  "Budots",
  "Changa tuki",
  "Dancehall pop",
  "Funk carioca",
  "Funk ostentação",
  "Melodic funk",
  "Proibidão",
  "Rasteirinha",
  "Merenhouse",
  "Nortec",
  "Rabòday",
  "Rara tech",
  "Russ music",
  "Shamstep",
  "Tribal guarachero",
  "Worldbeat",
  "Manila sound",
  "Funk",
  "Acid jazz",
  "Funktronica",
  "Synth-funk",
  "Jungle",
  "Ragga jungle",
  "Hardcore",
  "Bouncy techno",
  "Breakcore",
  "Raggacore",
  "Digital hardcore",
  "Doomcore",
  "Frenchcore",
  "Gabber",
  "Early hardcore",
  "Mainstream hardcore",
  "Happy hardcore",
  "UK hardcore",
  "Industrial hardcore",
  "J-core",
  "Lento violento",
  "Mákina",
  "Speedcore",
  "Extratone",
  "Flashcore",
  "Hypertone",
  "Splittercore",
  "Hardstyle",
  "Dubstyle",
  "Euphoric frenchcore",
  "Euphoric hardstyle",
  "Jumpstyle",
  "Rawstyle",
  "Trapstyle",
  "Hauntology",
  "Chillwave",
  "Hypnagogic pop",
  "Synthwave",
  "Darksynth",
  "Sovietwave",
  "Vaporwave",
  "Dreampunk",
  "Future funk",
  "Hardvapour",
  "Mallsoft",
  "Hip hop",
  "Afroswing",
  "Alternative hip hop",
  "Hipster hop",
  "Cloud rap",
  "Crunk",
  "Crunkcore",
  "Snap music",
  "Electro",
  "Latin freestyle",
  "Emo rap",
  "Instrumental hip hop",
  "Lofi hip hop",
  "Miami bass",
  "Mumble rap",
  "Trap",
  "Afro trap",
  "Drill",
  "UK drill",
  "Latin trap",
  "Phonk",
  "Trap (EDM)",
  "UK trap",
  "House music",
  "Acid house",
  "Afro house",
  "Amapiano",
  "Gqom",
  "Kidandali",
  "Kwaito",
  "Ambient house",
  "Balearic beat",
  "Ballroom",
  "Bass house",
  "Blog house",
  "Brazilian bass",
  "Slap house",
  "Chicago hard house",
  "Chicago house",
  "Deep house",
  "Disco house",
  "Diva house",
  "Hardbag",
  "Electro house",
  "Big room house",
  "Complextro",
  "Dutch house",
  "Fidget house",
  "Melbourne bounce",
  "Electro swing",
  "Eurohouse",
  "French house",
  "Funky house",
  "Future house",
  "Garage house",
  "Ghetto house",
  "Ghettotech",
  "Juke house",
  "Hip house",
  "Italo house",
  "Jazz house",
  "Latin house",
  "Melodic house",
  "Microhouse",
  "Moombahcore",
  "Moombahton",
  "Moombahsoul",
  "New Jersey sound",
  "Outsider house",
  "Progressive house",
  "Soulful house",
  "Tech house",
  "Tribal house",
  "Tropical house",
  "UK hard house",
  "Hard NRG",
  "Pumping house",
  "Hardbass",
  "Scouse house",
  "Industrial",
  "Deconstructed club",
  "Electro-industrial",
  "Dark electro",
  "Aggrotech",
  "Electronic body music (EBM)",
  "Futurepop",
  "New beat",
  "Industrial hip hop",
  "Industrial metal",
  "Cyber metal",
  "Neue Deutsche Härte",
  "Industrial rock",
  "Martial industrial",
  "Witch house",
  "Intelligent dance music (IDM)",
  "Drill 'n' bass",
  "Glitch",
  "Glitch hop",
  "Neo soul",
  "Nightcore",
  "Noise music",
  "Danger music",
  "Harsh noise",
  "Harsh noise wall",
  "Japanoise",
  "Power electronics",
  "Death industrial",
  "Power noise",
  "Plunderphonics",
  "Sampledelia",
  "Techno",
  "Acid techno",
  "Ambient techno",
  "Birmingham sound",
  "Bleep techno",
  "Detroit techno",
  "Dub techno",
  "Hardtechno",
  "Free tekno",
  "Jungletek",
  "Raggatek",
  "Industrial techno",
  "Minimal techno",
  "Schaffel",
  "Toytown techno",
  "Tecno brega",
  "Trance music",
  "Acid trance",
  "Balearic trance",
  "Dream trance",
  "Eurotrance",
  "Hands up",
  "Goa trance",
  "Nitzhonot",
  "Hard trance",
  "Progressive trance",
  "Psychedelic trance",
  "Dark psytrance",
  "Full-on",
  "Minimal psytrance",
  "Progressive psytrance",
  "Suomisaundi",
  "Zenonesque",
  "Tech trance",
  "Uplifting trance",
  "Vocal trance",
  "UK garage",
  "2-step garage",
  "Bassline",
  "Breakstep",
  "Dubstep",
  "Brostep",
  "Post-dubstep",
  "Reggaestep",
  "Riddim",
  "Future garage",
  "Grime",
  "Grindie",
  "Speed garage",
  "UK funky",
  "Funkstep",
  "Wonky",
  "Video game music",
  "Chiptune",
  "Bitpop",
  "Nintendocore",
  "Skweee",
  "FM synthesis",
  "Sequencer music",
  "American folk revival",
  "Americana",
  "Anti-folk",
  "British folk revival",
  "Celtic music",
  "Chalga",
  "Corrido",
  "Filk",
  "Folk rock",
  "Celtic rock",
  "Freak folk",
  "Indie folk",
  "Industrial folk",
  "Mariachi",
  "Ranchera",
  "Neofolk",
  "Progressive folk",
  "Protest song",
  "Psychedelic folk",
  "Singer-songwriter",
  "Nueva canción",
  "Skiffle",
  "Sung poetry",
  "Alternative hip hop",
  "Hipster hop",
  "Boom bap",
  "Bounce",
  "British hip hop",
  "Road rap",
  "Chopped and screwed",
  "Chopper",
  "Cloud rap",
  "Comedy hip hop",
  "Crunk",
  "Crunkcore",
  "Country rap",
  "East Coast hip hop",
  "Emo rap",
  "Freestyle rap",
  "G-funk",
  "Hardcore hip hop",
  "Dirty rap",
  "Gangsta rap",
  "Mafioso rap",
  "Horrorcore",
  "Memphis rap",
  "Hip hop soul",
  "Hyphy",
  "Jerkin'",
  "Industrial hip hop",
  "Instrumental hip hop",
  "Jazz rap",
  "Latin hip hop",
  "Chicano rap",
  "Lofi hip hop",
  "Miami bass",
  "Mumble rap",
  "Nerdcore",
  "Chap hop",
  "New jack swing",
  "Political hip hop",
  "Conscious hip hop",
  "Pop rap",
  "Progressive rap",
  "Punk rap",
  "Ragga hip hop",
  "Rap opera",
  "Rap rock",
  "Rap metal",
  "Trap metal",
  "Rapcore",
  "Religious hip hop",
  "Christian hip hop",
  "Jewish hip hop",
  "Snap",
  "Southern hip hop",
  "Trap",
  "Drill",
  "Brooklyn drill",
  "UK drill",
  "Latin trap",
  "Phonk",
  "Tread",
  "Turntablism",
  "Underground hip hop",
  "West Coast hip hop",
  "Acid jazz",
  "Afro-Cuban jazz",
  "Alt-jazz",
  "Avant-garde jazz",
  "Bebop",
  "Boogie-woogie",
  "Bossa nova",
  "Brazilian Jazz",
  "British dance band",
  "Cape jazz",
  "Chamber jazz",
  "Continental jazz",
  "Cool jazz",
  "Crossover jazz",
  "Dixieland",
  "Ethno jazz",
  "European free jazz",
  "Free funk",
  "Free improvisation",
  "Free jazz",
  "Gypsy jazz",
  "Hard bop",
  "Jazz blues",
  "Jazz-funk",
  "Jazz fusion",
  "Jazz rap",
  "Jazz rock",
  "Kansas City jazz",
  "Latin jazz",
  "Livetronica",
  "M-base",
  "Mainstream jazz",
  "Modal jazz",
  "Neo-bop jazz",
  "Neo-swing",
  "Novelty ragtime",
  "Nu jazz",
  "Orchestral jazz",
  "Post-bop",
  "Progressive jazz",
  "Punk jazz",
  "Ragtime",
  "Samba-jazz",
  "Shibuya-kei",
  "Ska jazz",
  "Smooth jazz",
  "Soul jazz",
  "Straight-ahead jazz",
  "Stride jazz",
  "Swing",
  "Trad jazz",
  "Third stream",
  "Vocal jazz",
  "West Coast jazz",
  "Adult album alternative",
  "Adult contemporary",
  "Ambient pop",
  "Arabic pop",
  "Art pop",
  "Baroque pop",
  "Bedroom pop",
  "Brill building",
  "Britpop",
  "Bubblegum pop",
  "C-pop",
  "Cantopop",
  "Hokkien pop",
  "Mandopop",
  "Canción",
  "Canzone",
  "Chalga",
  "Chamber pop",
  "Chanson",
  "Christian pop",
  "Classic hits",
  "Classical crossover",
  "Country pop",
  "Cringe pop",
  "Dance-pop",
  "Disco polo",
  "Electropop",
  "Europop",
  "Austropop",
  "Eurobeat",
  "French pop",
  "Italo dance",
  "Italo disco",
  "Laïkó",
  "Nederpop",
  "Neomelodic music",
  "Russian pop",
  "Fado",
  "Folk pop",
  "Hyperpop",
  "Indie pop",
  "Twee pop",
  "Indian pop",
  "Iranian pop",
  "J-pop",
  "City pop",
  "Shibuya-kei",
  "Jangle pop",
  "Jazz pop",
  "K-pop",
  "Korean hip hop",
  "Korean rock",
  "T'ong guitar",
  "Trot",
  "Latin ballad",
  "Latin pop",
  "Mexican pop",
  "New Romantic",
  "Oldies",
  "Operatic pop",
  "OPM",
  "Pinoy pop",
  "Pop rap",
  "Pop rock",
  "Pop punk",
  "Emo pop",
  "Neon pop",
  "Power pop",
  "Soft rock",
  "Surf pop",
  "Yacht rock",
  "Pop soul",
  "Progressive pop",
  "Psychedelic pop",
  "Rebetiko",
  "Schlager",
  "Sophisti-pop",
  "Space age pop",
  "Sunshine pop",
  "Swamp pop",
  "Synthpop",
  "Teen pop",
  "Traditional pop",
  "Turbo-folk",
  "Turkish pop",
  "Vispop",
  "Wonky pop",
  "Worldbeat",
  "Yé-yé",
  "Alternative R&B",
  "Contemporary R&B",
  "Disco",
  "Freestyle",
  "Go-go",
  "Funk",
  "Deep funk",
  "Minneapolis Sound",
  "Psychedelic funk",
  "Gospel music",
  "New jack swing",
  "Post-disco",
  "Boogie",
  "Rhythm and blues",
  "Doo-wop",
  "Soul",
  "Blue-eyed soul",
  "Hip hop soul",
  "Neo soul",
  "Northern soul",
  "Psychedelic soul",
  "Southern soul",
  "Afro rock",
  "Alternative rock",
  "Alternative dance",
  "Britpop",
  "Post-Britpop",
  "Dream pop",
  "Goth Rock",
  "Shoegaze",
  "Blackgaze",
  "Grunge",
  "Post-grunge",
  "Indie rock",
  "Dunedin sound",
  "Math rock",
  "Post-punk revival",
  "Madchester",
  "Baggy",
  "Noise pop",
  "Sadcore",
  "Slowcore",
  "Beat",
  "British Invasion",
  "Freakbeat",
  "Nederbeat",
  "Blues rock",
  "Boogie rock",
  "British rhythm and blues",
  "Chamber pop",
  "Christian rock",
  "Classic rock",
  "Comedy rock",
  "Country rock",
  "Dark cabaret",
  "Electronic rock",
  "Electronicore",
  "New wave",
  "Cold wave",
  "Dark wave",
  "Ethereal wave",
  "Experimental rock",
  "Art rock",
  "Industrial rock",
  "Post-punk",
  "Dance-punk",
  "Gothic rock",
  "No wave",
  "Noise rock",
  "Post-rock",
  "Post-metal",
  "Folk rock",
  "British folk rock",
  "Celtic rock",
  "Medieval folk rock",
  "Funk rock",
  "Garage rock",
  "Glam rock",
  "Hard rock",
  "Heartland rock",
  "Instrumental rock",
  "Jazz fusion",
  "Jazz rock",
  "Latin rock",
  "Mangue bit",
  "Metal",
  "Paisley Underground",
  "Desert rock",
  "Pop rock",
  "Jangle pop",
  "Power pop",
  "Soft rock",
  "Yacht rock",
  "Progressive rock",
  "Art rock",
  "Avant-prog",
  "Rock in Opposition",
  "Canterbury scene",
  "Flamenco rock",
  "Krautrock",
  "Neo-progressive rock",
  "New prog",
  "Post-progressive",
  "Space rock",
  "Symphonic Rock",
  "Psychedelic rock",
  "Acid rock",
  "Neo-psychedelia",
  "Raga rock",
  "Pub rock (Australia)",
  "Pub rock (United Kingdom)",
  "Punk rock",
  "Rap rock",
  "Rapcore",
  "Reggae rock",
  "Rock and roll",
  "Rockabilly",
  "Rock opera",
  "Roots rock",
  "Southern rock",
  "Stoner rock",
  "Swamp rock",
  "Sufi rock",
  "Surf rock",
  "Tropical rock",
  "Visual kei",
  "Nagoya kei",
  "Wizard rock",
  "Worldbeat",
  "World fusion",
  "Alternative metal",
  "Funk metal",
  "Nu metal",
  "Rap metal",
  "Avant-garde metal",
  "Black metal",
  "blackened death metal",
  "Atmospheric black metal",
  "Blackgaze",
  "Melodic black metal",
  "National Socialist black metal",
  "Symphonic black metal",
  "Viking metal",
  "War metal",
  "Christian metal",
  "Unblack metal",
  "Death metal",
  "Death 'n' roll",
  "Deathgrind",
  "Melodic death metal",
  "Technical death metal",
  "Doom metal",
  "Death-doom",
  "Drone metal",
  "Folk metal",
  "Celtic metal",
  "Medieval metal",
  "Pagan metal",
  "Glam metal",
  "Gothic metal",
  "Heavy metal",
  "Industrial metal",
  "Kawaii metal",
  "Latin metal",
  "Metalcore",
  "Deathcore",
  "Mathcore",
  "Melodic metalcore",
  "Neoclassical metal",
  "Neue Deutsche Härte",
  "Nintendocore",
  "Pirate metal",
  "Post-metal",
  "Power metal",
  "Progressive metal",
  "Djent",
  "Sludge metal",
  "Speed metal",
  "Symphonic metal",
  "Thrash metal",
  "Crossover thrash",
  "Groove metal",
  "Anarcho punk",
  "Crust punk",
  "D-beat",
  "Art punk",
  "Christian punk",
  "Deathrock",
  "Digital hardcore",
  "Folk punk",
  "Celtic punk",
  "Cowpunk",
  "Gypsy punk",
  "Garage punk",
  "Grindcore",
  "Crustgrind",
  "Goregrind",
  "Noisegrind",
  "Pornogrind",
  "Hardcore punk",
  "Crossover thrash",
  "Melodic hardcore",
  "Post-hardcore",
  "Emo",
  "Emo pop",
  "Screamo",
  "Powerviolence",
  "Street punk",
  "Thrashcore",
  "Horror punk",
  "Nazi punk",
  "Oi!",
  "Pop punk",
  "Easycore",
  "Neon pop",
  "Psychobilly",
  "Punk pathetique",
  "Riot grrrl",
  "Ska punk",
  "Skate punk",
  "African heavy metal",
  "African hip hop",
  "African popular music",
  "Afro house",
  "Afro pop",
  "Afrobeat",
  "Afrobeats",
  "Amapiano",
  "Apala",
  "Arabesque",
  "Benga",
  "Bikutsi",
  "Bongo flava",
  "Boomba",
  "Cape jazz",
  "Chaabi",
  "Chalga",
  "Chaoui music",
  "Chimurenga",
  "Congolese rumba",
  "Coupé-Décalé",
  "Fuji music",
  "Genge",
  "Gnawa",
  "Gqom",
  "Highlife",
  "Hiplife",
  "Igbo highlife",
  "Igbo rap",
  "Isicathamiya",
  "Jit",
  "Jùjú",
  "Kadongo Kamu",
  "Kizomba",
  "Kuduro",
  "Kwaito",
  "Kwela",
  "Makossa",
  "Maloya",
  "Ma'luf",
  "Marabi",
  "Marrabenta",
  "Mbalax",
  "Mbaqanga",
  "Mbube",
  "Morna",
  "Ndombolo",
  "Palm-wine",
  "Raï",
  "Sakara",
  "Sega",
  "Seggae",
  "Semba",
  "Shangaan electro",
  "Soukous",
  "Kwassa kwassa",
  "Taarab",
  "Zamrock",
  "Zouglou",
  "C-pop",
  "Cantopop",
  "Hokkien pop",
  "Mandopop",
  "Chinese hip hop",
  "Chinese folk music",
  "Chinese rock",
  "Hong Kong English pop",
  "Hong Kong hip hop",
  "Taiwanese hip hop",
  "Taiwanese pop",
  "Taiwanese rock",
  "Enka",
  "J-pop",
  "Japanese hip hop",
  "Japanese jazz",
  "Japanese rock",
  "Kayōkyoku",
  "K-pop",
  "Korean folk music",
  "Korean hip hop",
  "Korean rock",
  "Trot",
  "Asian Underground",
  "Baila",
  "Baul",
  "Bhangra",
  "Bhawaiya",
  "Dohori",
  "Filmi",
  "Indian classical",
  "Carnatic",
  "Hindustani classical",
  "Indian jazz",
  "Indian pop",
  "Indian rock",
  "Raga rock",
  "Kuthu",
  "Lavani",
  "Morlam",
  "Ragini",
  "Sufi rock",
  "Gamelan",
  "Malaysian hip hop",
  "Malaysian pop",
  "Malaysian rock",
  "Dangdut",
  "Indo pop",
  "Sundanese pop",
  "Keroncong",
  "Luk thung",
  "Luk krung",
  "Thai pop",
  "Thai string pop",
  "Manila sound",
  "Original Pilipino",
  "Pinoy pop",
  "Pinoy rock",
  "L-pop",
  "Mor lam",
  "V-pop",
  "Arabic music",
  "Arabic pop music",
  "Fann at-Tanbura",
  "Fijiri",
  "Khaliji",
  "Liwa",
  "Sawt",
  "Baithak Gana",
  "Bouyon",
  "Cadence-lypso",
  "Calypso",
  "Cha-cha-chá",
  "Chutney",
  "Chutney soca",
  "Chutney parang",
  "Compas",
  "Dancehall",
  "Mambo",
  "Mento",
  "Merengue",
  "Méringue",
  "Mozambique",
  "Pichakaree",
  "Punta",
  "Punta rock",
  "Rasin",
  "Reggae",
  "Dub",
  "Lovers rock",
  "Ragga",
  "Reggae fusion",
  "Ragga jungle",
  "Reggae rock",
  "Reggaeton",
  "Roots reggae",
  "Rocksteady",
  "Rumba",
  "Salsa",
  "Ska",
  "Ska punk",
  "Two-tone",
  "Soca",
  "Power soca",
  "Son cubano",
  "Songo",
  "Timba",
  "Twoubadou",
  "Zouk",
  "Axé",
  "Brazilian rock",
  "Brega",
  "Tecnobrega",
  "Choro",
  "Forró",
  "Frevo",
  "Funk carioca",
  "Lambada",
  "Zouk-Lambada",
  "Maracatu",
  "Música popular brasileira",
  "Tropicalia",
  "Música sertaneja",
  "Samba",
  "Pagode",
  "Samba rock",
  "Boogaloo",
  "Bullerengue",
  "Flamenco",
  "Cantes de ida y vuelta",
  "Fandangos",
  "Soleá",
  "Alegrías",
  "Bulerías",
  "Peteneras",
  "Tango",
  "Toná",
  "Martinetes",
  "Tonás",
  "Grupera",
  "Latin Christian",
  "Latin pop",
  "Latin ballad",
  "Latin rock",
  "Latin alternative",
  "Rock en Español",
  "Latin jazz",
  "Afro-Cuban jazz",
  "Bossa nova",
  "Mariachi",
  "Ranchera",
  "Reggaeton",
  "Latin trap",
  "Regional Mexican",
  "Banda",
  "Norteño",
  "Tango",
  "Tropical",
  "Bachata",
  "Bolero",
  "Criolla",
  "Cumbia",
  "Chicha",
  "Porro",
  "Guajira",
  "Mambo",
  "Merengue",
  "Rumba",
  "Salsa",
  "Salsa romántica",
  "Son",
  "Tejano",
  "Timba",
  "Tropipop",
  "Vallenato",
  "Buddhist music",
  "Christian music",
  "Church music",
  "Spirituals",
  "Gregorian chant",
  "Islamic music",
  "Hymn",
  "Liturgical music",
  "Latin folk",
  "Fado",
  "Huayno",
  "Son mexicano",
  "Música criolla",
];
